apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  labels:
    app.kubernetes.io/managed-by: Helm
    app: {{ .Release.Name }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: default
data:
  DB_SERVER: "192.168.1.55"
  DB_NAME: "NewAppDB"
