apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  labels:
    app.kubernetes.io/managed-by: Helm
    app: {{ .Release.Name }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: default
type: Opaque
stringData:
  DB_USER: "sa"
  DB_PASSWORD: "StrongPasswor123"
