apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-login-service
  labels:
    app: login
spec:
  selector:
    app: login
  ports:
    - port: {{ .Values.login.service.port }}
      targetPort: {{ .Values.login.service.targetPort }}
  type: ClusterIP
