apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-user-service
  labels:
    app: user
spec:
  selector:
    app: user
  ports:
    - port: {{ .Values.user.service.port }}
      targetPort: {{ .Values.user.service.targetPort }}
  type: ClusterIP
